runtime: nodejs18
env_variables:
  MONGODB_URI: "mongodb+srv://root:123@cluster0.xcngubw.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"  # Replace with your actual MongoDB connection URI
  GOOGLE_APPLICATION_CREDENTIALS: "KEY_FILE.json"
  KEY_RESOURCE: "projects/securityproject-418118/locations/global/keyRings/keyring/cryptoKeys/keyone"
  PROJECT_ID: "securityproject-418118"
